/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginpackage;

import com.client.FrameUI;
import java.awt.Color;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import static loginpackage.DialogFrame.signupForm;
import remoteserver.RemoteServerInterface;


/**
 *
 * @author Flex
 */
public class SignupForm extends javax.swing.JDialog {

    private static RemoteServerInterface server;
    private ArrayList<Map<String, Object>> map;
    private FrameUI mainframe;
    private static SignupForm signupform;

    public SignupForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();   
    }
    
    
    
    public static void setServer(RemoteServerInterface server){
       SignupForm.server = server;
    }
    
    public static void setSignUpInstance(SignupForm signupform){
      SignupForm.signupform = signupform; 
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        d_cancelbut = new javax.swing.JButton();
        d_okbut = new javax.swing.JButton();
        d_holder_pass = new javax.swing.JPasswordField();
        d_branch_name = new javax.swing.JComboBox<>();
        instead_search = new javax.swing.JTextField();
        label_d = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        d_holder_email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        d_pcholder = new javax.swing.JTextField();
        d_branch_Id = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SignUp");

        dialogpanel.setBackground(new java.awt.Color(5, 16, 72));
        dialogpanel.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SignUp Form");
        dialogpanel.add(jLabel2);
        jLabel2.setBounds(170, 20, 370, 50);

        jSeparator1.setForeground(new java.awt.Color(204, 255, 255));
        dialogpanel.add(jSeparator1);
        jSeparator1.setBounds(90, 80, 550, 10);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Branch ID :");
        dialogpanel.add(jLabel3);
        jLabel3.setBounds(50, 280, 140, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Branch :");
        dialogpanel.add(jLabel4);
        jLabel4.setBounds(80, 130, 110, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("User Name :");
        dialogpanel.add(jLabel6);
        jLabel6.setBounds(40, 380, 150, 50);

        d_cancelbut.setBackground(new java.awt.Color(153, 153, 153));
        d_cancelbut.setForeground(new java.awt.Color(255, 255, 255));
        d_cancelbut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clear.png"))); // NOI18N
        d_cancelbut.setToolTipText("");
        d_cancelbut.setBorder(null);
        d_cancelbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d_cancelbutActionPerformed(evt);
            }
        });
        dialogpanel.add(d_cancelbut);
        d_cancelbut.setBounds(450, 650, 80, 40);

        d_okbut.setBackground(new java.awt.Color(102, 102, 102));
        d_okbut.setForeground(new java.awt.Color(255, 255, 255));
        d_okbut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/approve.png"))); // NOI18N
        d_okbut.setBorder(null);
        d_okbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d_okbutActionPerformed(evt);
            }
        });
        dialogpanel.add(d_okbut);
        d_okbut.setBounds(550, 650, 70, 40);

        d_holder_pass.setBackground(new java.awt.Color(0,0,0,100));
        d_holder_pass.setFont(new java.awt.Font("Goudy Stout", 1, 24)); // NOI18N
        d_holder_pass.setForeground(new java.awt.Color(255, 255, 255));
        d_holder_pass.setBorder(null);
        d_holder_pass.setEchoChar('.');
        dialogpanel.add(d_holder_pass);
        d_holder_pass.setBounds(230, 570, 390, 50);

        d_branch_name.setBackground(new java.awt.Color(204, 204, 204));
        d_branch_name.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        d_branch_name.setForeground(new java.awt.Color(204, 204, 255));
        dialogpanel.add(d_branch_name);
        d_branch_name.setBounds(220, 130, 400, 50);

        instead_search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instead_search.setToolTipText("search instead");
        instead_search.setName(""); // NOI18N
        instead_search.setOpaque(false);
        instead_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instead_searchActionPerformed(evt);
            }
        });
        dialogpanel.add(instead_search);
        instead_search.setBounds(390, 200, 230, 30);

        label_d.setForeground(new java.awt.Color(255, 255, 255));
        label_d.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_d.setText("Search branch instead >>");
        dialogpanel.add(label_d);
        label_d.setBounds(220, 200, 160, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 153));
        jLabel8.setText("<< Back To Login");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        dialogpanel.add(jLabel8);
        jLabel8.setBounds(10, 710, 140, 30);

        d_holder_email.setBackground(new java.awt.Color(0,0,0,100));
        d_holder_email.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        d_holder_email.setForeground(new java.awt.Color(255, 255, 255));
        d_holder_email.setBorder(null);
        dialogpanel.add(d_holder_email);
        d_holder_email.setBounds(230, 470, 390, 50);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Email :");
        dialogpanel.add(jLabel9);
        jLabel9.setBounds(50, 470, 140, 50);

        d_pcholder.setBackground(new java.awt.Color(0,0,0,100));
        d_pcholder.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        d_pcholder.setForeground(new java.awt.Color(255, 255, 255));
        d_pcholder.setBorder(null);
        dialogpanel.add(d_pcholder);
        d_pcholder.setBounds(230, 380, 390, 50);

        d_branch_Id.setBackground(new java.awt.Color(0,0,0,100));
        d_branch_Id.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        d_branch_Id.setForeground(new java.awt.Color(255, 255, 255));
        d_branch_Id.setBorder(null);
        dialogpanel.add(d_branch_Id);
        d_branch_Id.setBounds(230, 280, 390, 50);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Password :");
        dialogpanel.add(jLabel10);
        jLabel10.setBounds(50, 570, 140, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dialogpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dialogpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void d_cancelbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d_cancelbutActionPerformed
        d_holder_email.setText("");
        d_holder_email.setText("");
        d_holder_pass.setText("");
        d_holder_email.setText("");
    }//GEN-LAST:event_d_cancelbutActionPerformed
    
    public void setupBranch() throws RemoteException, SQLException{
       String query = "SELECT Name From branch";
       map = server.selectFromDb(query);
       if(!map.isEmpty()){
         for(int i=0 ; i<map.size(); i++){
           d_branch_name.addItem(map.get(i).get("Name").toString());
         }
       }  
    }
    
    /******* Check Empty Data *****/
    
    public boolean hasEmpty(String id, String name , String email, String pass){
      if(id.trim().isEmpty() || name.trim().isEmpty() || email.trim().isEmpty() || pass.trim().isEmpty()){
         return true;
      }else
          return false;
    } 
    
   
    
   /** Input verifier for data **/
    public boolean verifyInput() throws RemoteException, SQLException{
      boolean valid = true;
      String branch = d_branch_name.getSelectedItem().toString();
      String id = d_branch_Id.getText();
      String holder = d_pcholder.getText();
      String email = d_holder_email.getText();
      String password = d_holder_pass.getText();
      Pattern regx = Pattern.compile("^[\\w!#$%&'*+/=?`{|}~^-]+(?:\\.[\\w!#$%&'*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$");
      Matcher matcher = regx.matcher(email);
      if(hasEmpty(id, holder, email, password)){
         JOptionPane.showMessageDialog(null,"Empty Data Entry is not allowed","Empty Entry",JOptionPane.ERROR_MESSAGE);
         valid = false;
      }else{
        if(password.trim().length() < 6){
           JOptionPane.showMessageDialog(null,"Password Length Must be Atleast 6 characters","Password Length",JOptionPane.ERROR_MESSAGE); 
           valid = false;
        }
        else if(!matcher.matches()){
           JOptionPane.showMessageDialog(null,"Wrong Email Format","Email Format",JOptionPane.ERROR_MESSAGE);  
           valid = false;
        }else{
            String query = "SELECT Name FROM branch WHERE ID='"+ id + "'";
            map = server.selectFromDb(query);
            if(!map.isEmpty()){
              query = "INSERT INTO holder values(0,'"+holder.trim()+"','"+email.trim()+"','"+password.trim()+"','"+id.trim()+"')";  
              server.insertToDb(query);
              valid = true;
            }else{
              JOptionPane.showMessageDialog(null,"No Branch Registerd With the given Branch ID","Incorrect ID",JOptionPane.WARNING_MESSAGE);
              valid = false;
            }
        }    
      }
     
      return valid;   
    }
    
    /***** confirm button event handler ******/
    private void d_okbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d_okbutActionPerformed
        try {
            if(verifyInput()){
                ImageIcon icon = new ImageIcon(getClass().getResource("/icons/success.png"));
                JOptionPane.showMessageDialog(null,"You Are Registered Successfully!","Success",JOptionPane.PLAIN_MESSAGE,icon);
                DialogFrame.setBranch(d_branch_name.getSelectedItem().toString());
                DialogFrame.setUser(d_pcholder.getText());
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        mainframe = new FrameUI();
                        mainframe.setVisible(true);
                        signupform.setVisible(false);
                        mainframe.branch_home.setText("Branch Name : "+ d_branch_name.getSelectedItem().toString());
                        mainframe.Id_home.setText("Branch Id : "+ d_branch_Id.getText());
                        DialogFrame.logindialog.setCounts();
                    }
                });
            }
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(null,ex.getCause(),"Remote Connection Error",JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,ex.getMessage(),"SQL Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_d_okbutActionPerformed

    private void instead_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instead_searchActionPerformed
        String val = instead_search.getText();
        instead_search.setText("");
        for(int i=0 ; i<d_branch_name.getItemCount(); i++){
         if(d_branch_name.getItemAt(i).toString().equalsIgnoreCase(val)){
            d_branch_name.setSelectedIndex(i);
            break;
         }
        }  
    }//GEN-LAST:event_instead_searchActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        signupForm.setVisible(false);
        DialogFrame.logindialog.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        jLabel8.setBorder(BorderFactory.createLineBorder(Color.WHITE));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        jLabel8.setBorder(null);
    }//GEN-LAST:event_jLabel8MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField d_branch_Id;
    private javax.swing.JComboBox<String> d_branch_name;
    private javax.swing.JButton d_cancelbut;
    private javax.swing.JTextField d_holder_email;
    private javax.swing.JPasswordField d_holder_pass;
    private javax.swing.JButton d_okbut;
    private javax.swing.JTextField d_pcholder;
    private javax.swing.JPanel dialogpanel;
    private javax.swing.JTextField instead_search;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_d;
    // End of variables declaration//GEN-END:variables
}
